spring:
  application:
    name: fulfillment-configuration-api
  security:
    oauth2:
      client:
        provider:
          sfcc:
            token-uri: http://test
        registration:
          sfcc:
            authorization-grant-type: client_credentials
            client-authentication-method: basic
            client-id: test
            client-secret: abcv
            scope:  mail
  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.order_inserts: true
      hibernate.jdbc.batch_size: 50
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      connection-test-query: SELECT 1
      jdbc-url: ${spring.datasource.url}
      maximum-pool-size: 25
      minimum-idle: 5
      pool-name: fulfillment-api-pool
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 240000
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
http:
  connect-timeout: 2000
  connection-request-timeout: 30000
  socket-timeout: 3000
  keep-alive-idle-connection: 300000
  validate-connection-after-ms: 5000
  max-connection-pool-size-total: 50
  max-connection-pool-size-per-route: 20
  max-retry-attempts: 3
  retry-period: 400
  max-retry-period: 1000
feign:
  client:
    refresh-enabled: true
  oauth2:
    enabled: true
    clientRegistrationId: sfcc
logging:
  env: local
  leanix-id: abc
  logBody: true
  config: classpath:logback-spring.xml
management:
  metrics:
    export:
      prometheus:
        enabled:  true
  endpoint:
    health:
      show-details: always
    configprops:
      enabled: true
    env:
      enabled: true
      keys-to-sanitize:
  endpoints:
    web:
      path-mapping:
        prometheus: /prometheus
      base-path:  /actuator
      exposure:
        include: health, prometheus
  health:
    diskspace:
      enabled: false
server:
  compression:
    enabled: true
sfcc:
  base-url:
    eu: http://test
  put-shipping-method-xml-url: test
  job-execution-url: test
  job-status-url: test
  job-status-retry:
    max-attempts: 10
    delay-ms: 500
